name: Ping
env:
  owner: mcadenaroa
  repo: automate101

on: 
  repository-dispatch:
    types: [run-ping]
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Install packages
      -run: npm ci
      -name: Run Tests
      -run: npm run ping
